version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/var/lib/redis
    ports:
      - "6379:6379"

volumes:
  redis_data:
    - DJANGO_SETTINGS_MODULE=yalla_shoot.settings